CREATE TABLE `properties` (
  `AgentRegistrationNo` varchar(255),
  `PropertyID` int NOT NULL AUTO_INCREMENT,
  `VideoID` int,
  `PhotoID` int,
  `ProjectName` varchar(255),
  `Town` varchar(255),
  `Block` varchar(255),
  `StreetName` varchar(255),
  `FlatType` varchar(255),
  `PostalDistrict` int,
  `MarketSegment` varchar(255),
  `Tenure` varchar(255),
  `TypeofSale` varchar(255),
  `LeaseCommenceDate` year,
  `RemainingLease` int,
  `NoofUnits` int,
  `Price` int,
  `FloorArea` int,
  `TypeofArea` varchar(255),
  `FloorLevel` varchar(255),
  `UnitPrice` int,
  `DateofSale` varchar(255),
  PRIMARY KEY (`PropertyID`)
)